### ISSUE TITLE
Running the project creation makes the current folder loses its own .git folder

### ISSUE THREAD

**Issue by lucasbento** [crocodilejs/crocodile-cli#4]
### Pratical example
Create a folder with `mkdir foobar`, then hit `cd foobar` and `git init`, make a blank commit in that folder and, in that same folder, run `crocodile chew foo_croc`, it will create `./foo_croc` but it will also affect git state of the `foobar` folder.

### Proposal
Since it seems that we can not change current working dir, we may check if the current directory has a `.git` folder, if it does, simply clone the boilerplate project into the new chosen folder, without removing boilerplate's previous commits.

What do you think, @niftylettuce?

**Comment by niftylettuce** [comment]
we should probably just detect if there's a .git in cwd, and if so, then throw an error saying "Sorry, please run this command in a folder outside of a git repository"

**Comment by niftylettuce** [comment]
I figured out how to fix 👍
